version: 2

models:
  - name: dim_players
    description: Dimension table containing player profiles and aggregated metrics
    columns:
      - name: player_id
        description: Unique player identifier
        tests:
          - unique
          - not_null
      - name: lifetime_revenue
        description: Total revenue from player
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: total_events
        description: Total number of events
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
  
  - name: fact_events
    description: Fact table for all player events
    columns:
      - name: event_id
        description: Unique event identifier
        tests:
          - unique
          - not_null
      - name: player_id
        description: Player who triggered event
        tests:
          - not_null
          - relationships:
              to: ref('dim_players')
              field: player_id
      - name: event_timestamp
        description: When event occurred
        tests:
          - not_null
  
  - name: fact_purchases
    description: Fact table for all purchase transactions
    columns:
      - name: transaction_id
        description: Unique transaction identifier
        tests:
          - unique
          - not_null
      - name: amount_usd
        description: Purchase amount in USD
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000
